### PR TITLE
Show answers only

### LINKED ISSUE #9: Add a toggle to mark post as answer and connect to the backend
**Part of User Story 1 (mark a post as answer)** 

Frontend: add a toggle in the frontend to mark a post as the answer to the topic. 

Acceptance criteria: visually looks good, UI makes sense to users and is consistent with current design. Work well with the backend.

### LINKED ISSUE #10: Add "answer" as a boolean field to database and implement function to toggle the field in the database
**Part of User Story 1 (mark a post as answer)** 

Backend: add "answer" as a boolean field for posts to the database. Implement functions to toggle the field in the database.  

Acceptance criteria: passes tests and works correctly with frontend implemented.

### LINKED ISSUE #11: Add a filter in topic with option "only show answers" and query backend
**Part of User Story 2 (filter posts to only show answer)**

Backend: query the database where the answer field is set to true and return that record to the front end display. Acceptance criteria: unit tested to ensure correct posts that are actually answers are returned after querying database.

_Note that this feature is dependent on first resolving issues #9 and #10._

### LINKED ISSUE #12: Write database queries and return a list of "answer" posts to the frontend
**Part of User Story 2 (filter posts to only show answer)**

Frontend: display the original post (i.e., the question) and then only display the reply/post marked as the answer right below.

Acceptance criteria: aesthetically pleasing visual design, UI makes sense to users and is consistent with current design. Interacts as expected with the backend.

_Note that this feature is dependent on first resolving issues #9 and #10._

### PR DESCRIPTION
**Pull request by cathlyt**
Implemented filer post as answer functionality.
Resolves #11 
Resolves #12

### CODE REVIEW

**Review by ziyanwang1 — COMMENTED** [review]
Looks good!

**Review by dmatovic — APPROVED** [review]
Looks good to me! Good job!

**Review by JimChen2002 — APPROVED** [review]
LGTM!

**Comment by cathlyt** [comment]
I linked the pull request to the wrong issue, this should be linked to #11 and #12, issue 15 is not related to this pull request

**Pull request merged**
